### ISSUE TITLE
Auto Complete with out new line

### ISSUE THREAD

**Issue by rajajan09** [angelozerr/tern.ace#6]
I found that auto complete works only if we add \n. Basically auto complete popup will be shown from second line in editor.
Is there a way to display auto complete in first line after var arr =[];

**Comment by angelozerr** [comment]
@rajajan09 I'm sorry I gave up this project.

Hope you will fix your problem. Good luck!

**Comment by rajajan09** [comment]
replace this method in tern-ace.js then it should work.

  function toTernLoc(pos) {
    if (typeof(pos.row!==undefined && pos.row>=0) return {line: pos.row, ch: pos.column};
    return pos;
  }

**Comment by angelozerr** [comment]
I suggest you create a PR and I could merge it if you wish

**Comment by rajajan09** [comment]
Done..check and close PR please .
